# Generated by Django 5.2.14 on 2026-05-30 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Proyek Baru', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='New', max_length=50)),
                ('html_draft', models.TextField(blank=True)),
                ('active_tab', models.CharField(blank=True, default='objectives', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
