# Generated by Django 5.2.14 on 2026-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='json_draft',
            field=models.TextField(blank=True),
        ),
    ]
