# Generated by Django 5.2.14 on 2026-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pm_project_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
